spring.application.name=SpringHomeworkJWT
# 8443 ? ??????? ????? ??? ??????????
server.port=8443

# ???? ? ????? ???????????
server.ssl.key-store=classpath:keystore.p12

# ?????? ??????? ??????? ??? ?????????
server.ssl.key-store-password=mypassword123

# ?????? ?????
server.ssl.key-store-type=PKCS12

# ??? ??????????? (alias ??????? ??????? ??? ?????????)
server.ssl.key-alias=myapp
